name: Generate ISO
on:
  workflow_dispatch: # Allows you to run this manually from the Actions tab
  schedule:
    - cron:  '0 0 * * 0' # Optional: Runs every Sunday at midnight

jobs:
  generate-iso:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate ISO
        uses: blue-build/github-action@v1
        with:
          cli_version: latest
          recipe: 'recipe.yml'
          registry: 'ghcr.io/benjaminbabbagebackup-eng'
          # We provide these even if we aren't using them to stop the "missing key" error
          registry_token: ${{ github.token }}
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
