name: Test Subject 1
on:
  schedule:
    - cron: '0 0 * * *' # Build daily to keep OGC kernel current
  push:
    branches:
      - main
  workflow_dispatch: # Allows you to manual start the build on GitHub website

jobs:
  bluebuild:
    name: Build Custom Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write  
    steps:
      - name: Build Custom Image
        uses: blue-build/github-action@v1
        env:
          COSIGN_EXPERIMENTAL: "1"   # ‚Üê this enables keyless mode in cosign
        with:
          recipe: 'recipes/recipe.yml'
          registry_token: ${{ github.token }}
          generate_iso: true
          rechunk: true
